export const burgerActionsTypes = {
    'ADD_INGREDIENT': 'ADD_INGREDIENT', 
    'REMOVE_INGREDIENT': 'REMOVE_INGREDIENT', 
    'SET_INGREDIENTS_LIST': 'SET_INGREDIENTS_LIST', 
    'FILL_ORDER': 'FILL_ORDER', 
}